name: Deploy base infra template

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy to
        required: true


# Environment variables - you need to define the respective github secrets
env:
  ARM_TEMPLATE_1: "./IaC/${{ secrets.AZURE_TEMPLATE_1 }}" #example: base.json
  ARM_TEMPLATE_2: "./IaC/${{ secrets.AZURE_TEMPLATE_2 }}" #optional - example: aks.json
  ARM_PARAM_FILE_1: "./IaC/parms/${{ secrets.AZURE_PARM_1 }}" #example: NORTHWIND-TRADERS-base-parm.json
  ARM_PARAM_FILE_2: "./IaC/parms/${{ secrets.AZURE_PARM_2 }}" #optional example: NORTHWIND-TRADERS-aks-parm.json
  LOCATION: "${{ secrets.AZURE_LOCATION }}" #example: NorthSwitzerland
  SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}" #example: 3a98dd0b-3278-4919-8a6f-01c3ebf51541
  APP_RESOURCE_GROUP: "${{ secrets.AZURE_RESOURCE_GROUP }}-rg"

jobs:
  validate_and_deploy_job:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env_to_deploy }}

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s "$SUBSCRIPTION_ID"
      
      - name: Create Azure resource group
        run: |
             az deployment sub create \
              --location $LOCATION \
              --template-file ./IaC/deployment-rg.bicep \
              --parameters name="$APP_RESOURCE_GROUP location="$LOCATION"
              
      - name: Validate deployment template(s)
        run: |
          az group deployment validate --resource-group "$APP_RESOURCE_GROUP" --template-file "$ARM_TEMPLATE_1"
