name: Deploy template(s)

# Deployment templates are expected in ./IaC/
#                    .... parameter in ./IaC/Parms
# Following secrets are expected in environment or repo secrets:
# AZURE_CREDENTIALS: Azure credentials, see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux for how to create these
# AZURE_LOCATION: Azure location, for example: NorthSwitzerland
# AZURE_SUBSCRIPTION_ID: Azure subscrition's id to deploy into, for example: 3a98dd0b-3278-4919-8a6f-01c3ebf51541
# AZURE_RESOURCE_GROUP: Resource group to create
# ARM_TEMPLATE_FILE_1: ARM template #1 - for example base.json
# ARM_PARM_FILE_1 for ARM_TEMPLATE_1 - for example NORTHWIND-TRADERS-base.parameters.json
#
# OPTIONAL:
#  ARM_TEMPLATE_FILE_2: second (optional) template to deploy, for example: aks.json
#  ARM_PARM_FILE_2: parm file for the second template file, for example: NORTHWIND-TRADERS-aks.parameters.json

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy to
        required: true

env:
  ARM_TEMPLATE_FILE_1: "./IaC/${{ secrets.AZURE_TEMPLATE_FILE_1 }}"
  ARM_TEMPLATE_FILE_2: "./IaC/${{ secrets.AZURE_TEMPLATE_FILE_2 }}"
  ARM_PARM_FILE_1: "./IaC/Parms/${{ secrets.ARM_PARM_FILE_1 }}"
  ARM_PARM_FILE_2: "./IaC/Parms/${{ secrets.ARM_PARM_FILE_2 }}"

jobs:
  validate_and_deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
      - name: Create Azure resource group
        run: |
             az deployment sub create \
              --location "${{ secrets.AZURE_LOCATION }}" \
              --template-file ./IaC/Utils/rg.bicep \
              --parameters name=${{ secrets.AZURE_RESOURCE_GROUP }} location=${{ secrets.AZURE_LOCATION }}
              
      - name: Validate deployment template #1
        run: |
          az group deployment validate --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file "$ARM_TEMPLATE_FILE_1" --parameters "$ARM_PARM_FILE_1"

      # - name: Validate deployment template #2
      #   run: |
      #     az group deployment validate --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file "$ARM_TEMPLATE_FILE_2" --parameters "$ARM_PARM_FILE_2"

      - name: Deploy template #1
        run: |
             az deployment group create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}  \
              --template-file "$ARM_TEMPLATE_FILE_1"  \
              --parameters "$ARM_PARM_FILE_1"

      # - name: Deploy template #2
      #   run: |
      #        az deployment group create \
      #         --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}  \
      #         --template-file "$ARM_TEMPLATE_FILE_2"  \
      #         --parameters "$ARM_PARM_FILE_2"
