name: Deploy template(s)

# Deployment templates are expected in ./IaC/
#                    .... parameter in ./IaC/Parms
# Following secrets are expected in environment or repo secrets:
# AZURE_CREDENTIALS: Azure credentials, see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux for how to create these
# LOCATION: Azure location, for example: NorthSwitzerland
# SUBSCRIPTION_ID: Azure subscrition's id to deploy into, for example: 3a98dd0b-3278-4919-8a6f-01c3ebf51541
# ARM_TEMPLATE_1: ARM template #1 - for example base.json
# ARM_PARAM_FILE_1 for ARM_TEMPLATE_1 - for example NORTHWIND-TRADERS-base-parm.json
#
# OPTIONAL:
#  ARM_TEMPLATE_2: second (optional) template to deploy, for example: aks.json
#  ARM_PARAM_FILE_2: parm file for the second template file, for example: NORTHWIND-TRADERS-aks-parm.json

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy to
        required: true

env:
  ARM_TEMPLATE_1: "./IaC/${{ secrets.AZURE_TEMPLATE_1 }}" #example: base.json
  ARM_TEMPLATE_2: "./IaC/${{ secrets.AZURE_TEMPLATE_2 }}" #optional - example: aks.json
  ARM_PARAM_FILE_1: "./IaC/Parms/${{ secrets.AZURE_PARM_1 }}" #example: NORTHWIND-TRADERS-base-parm.json
  ARM_PARAM_FILE_2: "./IaC/Parms/${{ secrets.AZURE_PARM_2 }}" #optional example: NORTHWIND-TRADERS-aks-parm.json
  APP_RESOURCE_GROUP: "${{ secrets.AZURE_RESOURCE_GROUP }}"

jobs:
  validate_and_deploy_job:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env_to_deploy }}

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
      - name: Create Azure resource group
        run: |
             az deployment sub create \
              --location "${{ secrets.AZURE_LOCATION }}" \
              --template-file ./IaC/utils/deployment-rg.bicep \
              --parameters name="$APP_RESOURCE_GROUP location="${{ secrets.AZURE_LOCATION }}"
              
      - name: Validate deployment template #1
        run: |
          az group deployment validate --resource-group "$APP_RESOURCE_GROUP" --template-file "$ARM_TEMPLATE_1" --parameters "$ARM_PARAM_FILE_1"

      - name: Validate deployment template #2
        run: |
          az group deployment validate --resource-group "$APP_RESOURCE_GROUP" --template-file "$ARM_TEMPLATE_2" --parameters "$ARM_PARAM_FILE_2"

      - name: Deploy template #1
        run: |
             az deployment group create \
              --resource-group "$APP_RESOURCE_GROUP"  \
              --template-file "$ARM_TEMPLATE_1"  \
              --parameters "$ARM_PARAM_FILE_1"

      - name: Deploy template #2
        run: |
             az deployment group create \
              --resource-group "$APP_RESOURCE_GROUP"  \
              --template-file "$ARM_TEMPLATE_2"  \
              --parameters "$ARM_PARAM_FILE_2"
